name: "RedstoneSpawnersReloaded"
version: "${project.version}"
author: "Trophonix, devilAPI"
main: "com.trophonix.redstonespawners.devilAPI.RedstoneSpawners"
api-version: 1.21
commands:
  redstonespawners:
    description: "RedstoneSpawners admin command"
    aliases: [rss]
    permission: "redstonespawners.admin"
permissions:
  redstonespawners.admin:
    default: "op"